/**
 * Generic storage-key safety.
 *
 * Object keys are generated by the server, but they are also echoed back from
 * the client (a story's saved `coverImage`), so every read and write runs the
 * key through this guard before touching a driver. Rejects traversal,
 * separators we do not use, control characters and anything oversized.
 * `.agent/skills/media-upload/SKILL.md` (path traversal).
 */
export const MAX_STORAGE_KEY_LENGTH = 512;

const UNSAFE = /[\u0000-\u001f\u007f\\]/;

export function isSafeStorageKey(key: string): boolean {
  if (key.length === 0 || key.length > MAX_STORAGE_KEY_LENGTH) {
    return false;
  }
  if (key.startsWith("/") || UNSAFE.test(key)) {
    return false;
  }
  // Reject any traversal segment.
  return !key.split("/").some((segment) => segment === "" || segment === "." || segment === "..");
}

/** Throws a `TypeError` for a key that must never reach a driver. */
export function assertSafeStorageKey(key: string): void {
  if (!isSafeStorageKey(key)) {
    throw new TypeError("Unsafe storage key.");
  }
}
